---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LYY.
--- DateTime: 2024/7/27 20:36
---
if(redis.call('get',KEYS[1])==ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0